lib/commands/help.js
lib/core/Manager.js

typo fixes

---

LICENSE

Update License Year to 2015

---

lib/commands/list.js

tiny change to punctuation when running `bower list`

change to use a standard three dot ellipsis

---

test/commands/install.js

Introduced in https://github.com/bower/bower/pull/1866.

Remove `it.only`.

---

package.json

Added keywords tag

---

lib/util/download.js
lib/util/userAgent.js

add User-Agent to downloadd

---

CHANGELOG.md
package.json

Lock lru-cache package

---

lib/abbreviations.js
lib/index.js
test/commands/bower.js
test/commands/index.js
test/helpers.js

I think now the index file, which is the main one will lock more clear

Move abbreviations to a different file

---

README.md

Signed-off-by: Kun Yan <kyan@redhat.com>

Add badge links to readme #2048 #2049

---

lib/core/resolvers/GitRemoteResolver.js

@sheerun review when you have time?

Fix shallow clone host

---

CONTRIBUTING.md

Instructions for squashing commits are helpful for new comers.

Adds instructions for squashing commits

---

package.json

context: https://github.com/bower/bower/issues/2118#issuecomment-168097858
Fixes #2118
----
much :cake: to @kbenjamin for being a champ helping to bisect this.. A++++ work
---
xref https://github.com/npm/fs-write-stream-atomic/issues/11

Lock fs-write-steam-atomic to 1.0.5

---

lib/commands/install.js
lib/commands/login.js
lib/util/git.js
test/util/git.js
test/util/index.js

* Remove unused 'return' after 'throw'
* Fix code quality issues

Display login message when user login via bower login

---

LICENSE
package.json

- Update license year to 2016
- package.json updated as per 1.7.2 release

Changes to license file and package.json

---

test/core/resolvers/pluginResolverFactory.js

This PR is still work in progress. Looking for feedback so that I know I'm headed the right direction.

Adds tests for pluginResolverFactory.js

---

CHANGELOG.md

Fixes https://github.com/bower/bower/issues/2184.

Changelog is still in 2015

---

Gruntfile.js

I checked the file and I saw that there were some require statements, so I thought in making a **jsonPackage** variable that read just once the file `package.json` file. So it can be used in all the cases.

Add jsonPackage for refactoring purposes

---

lib/templates/std/conflict.std

I think that just by clarifying the statement we could avoid some confusions as in #1714.

Extend conflict message

---

lib/renderers/JsonRenderer.js
lib/renderers/StandardRenderer.js
lib/util/rootCheck.js

- jscs is removed from the project.

Remove jscs inline error suppression comments.

---

CONTRIBUTING.md

- remove trailing whitespace
- "anyway" -> "any way"

Fix grammar in contributing file.

---

lib/commands/register.js
test/commands/register.js

This is a follow-up to the #2248.

Support single-char repo names and package names

---

lib/templates/std/help-cache.std

fix for 2264

---

lib/bin/bower.js

#2075  - Info message showed for bower register instead of error message

info message added for bower register

---

test/commands/install.js

Created new integration test for issue #1513. All of the new integration tests succeed - is it possible #1513 has been resolved some other way? It has been about a year since it was last discussed..

Added integration tests for installing nested components (#1513)

---

lib/commands/lookup.js
lib/core/Manager.js
lib/core/resolvers/GitResolver.js

This fixes a few minor JavaScript issues found by [lgtm](https://lgtm.com); for more details see https://lgtm.com/projects/g/bower/bower.
Each commit fixes one particular kind of issue; let me know if you'd prefer a different organisation.
(Full disclosure: I work on lgtm's JavaScript analysis.)

Fix issues found by lgtm
