bower/bower

lib/core/Manager.js
This only shows up with dependency conflicts arise, but it had two colons.
From this:
```
? Answer:: 
```
To this:
```
? Answer:
```
Steps to reproduce:
* Try to install two conflicting module versions.
Should affect all platforms.
Let me know if there's anything else that is needed.
=> Remove erroneous colon.

templates/std/conflict.std
Adding new line to prefix notice, see #1639
=> Fix for #1639, missing line break in CLI input

lib/commands/install.js, lib/core/Project.js, templates/json/help-install.json, test/commands/install.js
=> Add --save-exact flag

lib/core/resolvers/GitHubResolver.js, lib/core/resolvers/GitRemoteResolver.js, test/core/resolvers/gitRemoteResolver.js
Added logic to automatically detect smart Git hosts that allow shallow cloning. This is done by sending an `ls-remote` request to the server and then evaluating the returned HTTP header fields. For this, Curl
verbose logging is enabled for the `ls-remote` request, since Curl verbose logging sends the returned HTTP headers to `stderr`.
If the `stderr` output contains the desired header
Content-Type: application/x-git-upload-pack-advertisement
then the server supports shallow cloning.
This approach uses Git and Curl for the heavy lifting. Instead of implementing the request to the server using a simple HTTP client, Git is used, since it takes care of authentication using stored credentials.
The used approach should also work for BitBucket, which only sends the Content-Type header when a …
=> Automatically detecting smart Git hosts

lib/commands/version.js, test/commands/version.js
When users of the programmatic API update the version, they may do so without having to inspect the new contents of the bower.json file to find out the new version.
This is useful in scripts where the tag needs to be pushed programatically; the user can push the new tag explicitly.
=> Fixes #1754: The version command in the programmatic API now returns the new version

package.json
Fixes the failing unit tests. The request dependency needs to be set to 2.53.0.
=> Request dep

README.md
The completion command appears to have been lost during the rewrite
(#1066).  So to avoid confusion it should not be mentioned in the
README.
=> doc: remove section about completion

package.json, test/core/resolveCache.js, test/core/resolvers/gitResolver.js, test/core/resolvers/svnResolver.js
Upgrading to latest version of semver to fix (#1817, #1845, #1851).
Possible breaking changes in regards to the way semvers handles pre-releases.
If a version has a prerelease tags (for example, 1.2.3-alpha.3) then it will only be allowed to satisfy comparator sets if at least one comparator with the same [major, minor, patch] tuple also has a prerelease tag.
For example, the range >1.2.3-alpha.0 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by * or 1.2.3. See [semvers](https://github.com/npm/node-semver#prerelease-tags) additional details.
=> upgrade to newer semver, fixes #1817,#1845,#1851

templates/json/help.json
"-v" shorthand aleady supported of cli opeion for output version
```
$ bower --version
$ bower -v
```
```
Usage:
bower <command> [<args>] [<options>]
Commands:
cache                   Manage bower cache
help                    Display help information about Bower
home                    Opens a package homepage into your favorite browser
info                    Info of a particular package
init                    Interactively create a bower.json file
install                 Install a package locally
link                    Symlink a package folder
list                    List local packages - and possible updates
login                   Authenticate with GitHub and store credentials
lookup                  Look up a package URL by name
prune                   Removes local extraneous …
```
=> Add shorthand for version of options in help.json

README.md
Instead, use link to contributors page on GitHub
=> Remove core team section from README

lib/config.js, package.json, test/commands/install.js
IMO it is more pleasant behavior. It tries to find bower.json in parent directories and fallbacks to config.cwd or process.cwd()
=> Make bower commands work from subdirectories

package.json
Installing bower locally if perfectly good. It allows to use different version of bower locally.
The next step is to create bower-cli package that can run local bower installation.
=> No longer prefer installing bower as global

lib/commands/init.js, test/commands/init.js
Hi!
While using `bower init` this morning, I noticed that the resulting bower.json file did not include the "private" key I had chosen a value for. It looks like the behavior of `mout.lang.isEmpty()` was [changed in mout v0.10.0](https://github.com/mout/mout/commit/d80a75510db77fa11e0b6cc795a7d1f432892457) ([discussion](https://github.com/mout/mout/issues/173)), and Bower's dependency on mout introduced this bug, preventing `bower init` from being able to create a complete bower.json.
Interestingly, this buggy(?) behavior [is captured in the bower test for init](https://github.com/bower/bower/blob/master/test/commands/init.js#L34), where the input includes "private", but it is not in the expected output, so forgive me if this behavior is in fact intended :).
Also, I almost never write …
=> Allow boolean values in bower.json file created by `bower init`

package.json, test/util/analytics.js
The purpose of this PR is to reduce issues with the usage statistics prompt. This is done by bumping to the latest version of Insight, which include a check for `process.env.CI` before showing the prompt and also adds a 30 second timeout to the prompt.
This should negate most (if not all) issues raised by #1102.
=> Bumps Insight to reduce prompt friction

lib/core/resolvers/GitResolver.js, lib/core/resolvers/SvnResolver.js, test/core/resolvers/gitResolver.js, test/core/resolvers/svnResolver.js
Prior to this commit, when specifying a package version that cannot
be resolved, but other versions are available, the error message
did not state which what package failed, allowing for confusion.
For example, you might see:
```
bower ENORESTARGET  No tag found that was able to satisfy 1.0.2
Additional error details:
Available versions: 1.0.1, 1.0.0
```
After this change, in the above situation the svn and git resolvers
will produce the following:
```
bower ENORESTARGET  No tag found that was able to satisfy 1.0.2
Additional error details:
Available versions in somelib: 1.0.1, 1.0.0
```
=> Include package name in error info when a version is not found.

lib/core/resolverFactory.js
This PR public pluggable resolvers configuration in **.bowerrc** to bower cli.   This will allow you to pass resolvers interactively especially in build task. e.g.:
```bash
bower install [optional pkg names] --config.resolvers="My-resolver1"
//or
bower install [optional pkg names] --config.resolvers="/Users/xxx/anypath/packagename"
//or
bower install [optional pkg names] --config.resolvers="/Users/xxx/anypath-without-comma/packagename, other-resolver-package-in-bowers-range"
```
=> allow --config.resolvers={required package}

README.md
The msysgit development environment was superseded by Git for Windows. In addition to the name change, the installer's screens changed a bit. I updated the text and screenshots accordingly.
=> Replace README file msysgit references with Git for Windows

lib/core/Manager.js, test/commands/install.js, test/commands/update.js
Fixes an issue with ignoredDependencies where they were not properly processed if a package with that dependency was already installed.  - Issue #1962
=> fix issue #1962 - ignoredDependenices multiple install run

lib/core/resolvers/SvnResolver.js
Prevents svn CLI client to hang forever with no feedback to the user, upon any server connection errors that request user input. Fixes #1968
=> use --non-interactive when running svn client

lib/core/resolvers/UrlResolver.js
[I discovered](https://github.com/Modernizr/modernizr-neue/issues/55) that urls with a trailing slash fail for Modernizr's use case. Because of where we add the zip (e.g. after the query string) the `fileName` prop is null. As a result it throws an error without this fix.
=> strip trailing slash in urlResolver

README.md
The readme said there is no need to run Bower with root permissions and I totally agree to that. Since [quite a few people use this in production](https://github.com/search?utf8=%E2%9C%93&q=file%3ADockerfile+%22--allow-root%22&type=Code&ref=searchresults), it might be a good idea to remove the flag from the most prominent part of the documentation.
=> remove hint to use --allow-root flag from readme

lib/util/download.js, test/util/download.js, test/util/index.js
options from download need to be pass to request library that make HTTP
request
Also when there is http error stream need to be closed otherwise there
is issue reported that unlink operation is not permitted on Windows
=> fix passing options to request

lib/config.js, npm-shrinkwrap.json, package.json, test/commands/install.js
Updates:
+ Add untildify module
+ Update config.js to convert tilde path to home path
Fixes #1784
=> Supports ~/ paths to cwd field in .bowerrc

test/commands/install.js
This test tries to run `bower install` when the `.bowerrc` specifies a directory that's actually a file. Super trivial, but it should increase coverage for /lib/util/fs.js to 100%. Also, my first pull request for Bower. Please let me know if anything needs changing.
=> Add directory test for install command

lib/core/resolvers/Resolver.js, test/core/resolvers/resolver.js
=> Remove @ in temporary directories

lib/commands/update.js, lib/core/Project.js, test/commands/update.js
This PR lets `bower update` update `bower.json` via a `--save` flag. It mimics [npm's update behavior](https://docs.npmjs.com/cli/update#recording-updates-with-save).
Current behavior:
- `bower update` updates components in `bower_components/` while respecting components' semver in `bower.json`. For example, if bootstrap is listed as `~2.2.0` in `bower.json`, running `bower update` will update `bower_components/bootstrap` to 2.2.2 because 2.2.2 is the latest version greater than 2.2.0 but less than 3.0.0.
- `bower.json` is not modified.
- Here are [steps to test this behavior locally](https://gist.github.com/contolini/c950b513f37aa6e754d2).
New behavior proposed by this PR:
- `bower update --save` does the same stuff above but it also edits `bower.json`. In the above example, bootstrap …
=> Add `bower update --save` functionality 

lib/core/Manager.js, lib/core/Project.js, test/commands/install.js, test/commands/update.js
Given:
```js
"dependencies": {
"component-one": "~1.0.0",
"component-two": "~1.0.0"
}
```
Running `bower update component-one` will update component-one *and* component-two. This is particularly problematic if you have dozens of dependencies because you'll be waiting for bower to download all of them when all you wanted was component-one. Running `bower install component-XYZ` does the same thing -- update every component.
This PR instructs the manager to only update the requested component(s).
General logic:
1. Store arguments passed to the install/update commands (the names of packages the user wants to install/update).
2. When it's time to fetch targets, only fetch targets that match the packages from step 1.
3. If no arguments were passed, fetch everything.
Related to #256, #924, #1770 …
=> Only update the packages requested by the user

lib/commands/index.js, lib/commands/search.js, lib/util/cli.js, test/commands/search.js
This PR aims to address issue #2066 by warning the user before attempting to list all packages when using `bower search` with no query parameter.
When running `bower search` with no additional params, the user should see the following:
```
? Running search with no search term will list all bower packages and may take a while to complete. Continue? (Y/n)
```
If they confirm the action, the search will be performed. If they deny the action, `No results.` will be printed and they will be returned to their prompt.
The search will just be performed without any prompt.
The PR includes tests that no prompt occurs in non-interactive mode (no prompt, just like it was before the PR), and tests that the full listing is generated in interactive mode if and only if the user agrees to continue past the …
=> Prompt before listing all repos when running `bower search` without a query param

lib/renderers/StandardRenderer.js, package.json, templates/std/info.std, test/renderers/StandardRenderer.js
Hides prereleases behind the `--verbose` flag. Fixes #2081.
Current behavior:
```
$ bower info angular
{
name: 'angular',
version: '1.4.8',
main: './angular.js',
ignore: [],
dependencies: {},
homepage: 'https://github.com/angular/bower-angular'
}
Available versions:
- 1.5.0-build.4422+sha.e94b37e
- 1.5.0-build.4421+sha.6976d6d
- 1.5.0-build.4420+sha.df6fade
- 1.5.0-build.4419+sha.983b059
- 1.5.0-build.4418+sha.983b059
- 1.5.0-build.4417+sha.25e8c59
- 1.5.0-build.4416+sha.6628b4f
- 1.5.0-build.4415+sha.6e18b50
- 1.5.0-build.4414+sha.77419cf
- 1.5.0-build.4413+sha.193153c
- 1.5.0-build.4412+sha.6a0686d
- 1.5.0-build.4411+sha.6a0686d
- 1.5.0-build.4410+sha.08c9a5e
- 1.5.0-build.4409+sha.a72c12b
- 1.5.0-build.4408+sha.73e3865
- 1.5.0-build.4407+sha.b641181
- 1.5.0-build.4406+sha.7ffb2d3
- …
```
=> Hide prerelease versions from `bower info`

templates/json/help-install.json, templates/json/help-register.json, templates/json/help-uninstall.json, templates/json/help-unregister.json
The `bower help` command will now display information on the `--force` option where it applies. This is for `install` `uninstall` `register` and `unregister`.
This was requested as per @sheerun on bower/bower.github.io#203
=> Added the --force docs to the --help command

lib/util/extract.js, test/commands/install.js
Prevent extraction failing if a package archive contains a file with the same name as the archive, or a single directory with a subdirectory with the same name.
The former was picked up from a TODO in the codebase, the latter from #1935.
=> Fix name clashes in package extraction

lib/commands/link.js, lib/core/Manager.js, lib/core/Project.js, lib/util/isPathAbsolute.js, lib/util/relativeToBaseDir.js, test/commands/install.js, test/commands/link.js, test/commands/uninstall.js, test/util/createLink.js, test/util/index.js, test/util/isPathAbsolute.js, test/util/relativeToBaseDir.js
As discussed in #1914 we want to support absolute paths in `.bowerrc` directory option. A simple check if the directory begin with a `/` decides whether the path is relative and prefixed with the current work directory or taken as absolute path.
=> support absolute path in .bowerrc directory option

lib/core/Manager.js
This fix brings us inline with how npm installs work and also brings us
more inline with how semver is supposed to be used.
Fixes #2144
=> Use caret on install save

lib/core/resolvers/GitResolver.js, test/core/resolvers/gitResolver.js
=> when strictSsl is false set GIT_SSL_NO_VERIFY=true for git command

lib/core/Project.js, test/commands/install.js, test/commands/uninstall.js
Hi all, 
I'm a long-time fan and user or bower, first-time PRer. I am grateful to bower's maintainers, and I'd be glad for any feedback or suggestions.
This PR is in response to issue #1040, specifically comments from @svengt and @sheerun. It adds support for npm-like config setting set in `.bowerrc`. When set to true, the "save" setting causes the install and uninstall commands to act as if the user had specified `--save`. Likewise, when set to true, the "save-exact" setting causes the install command to act as if the user had specified `--save-exact`. So as not to break the API, when set to false or omitted, these commands behave as before.
One small note: [`lib/commands/install.js`](https://github.com/bower/bower/blob/master/lib/commands/install.js#L12) already checked for a …
=> add support for save and save-exact in .bowerrc

lib/core/scripts.js, test/core/scripts.js
Fixes #2174 
> % character replaced only on the first occurance in each of .bowerrc scripts
=> Replace all occurrences of % character in hook commands.

.eslintrc
Changed the indentation from 2 to 4 spaces in .eslintrc files.
All the code is using this convention and .jscsrc already define 4 as
the right value.
=> [eslint] fix indentation to 4 spaces

README.md
This commit will change copyright year from 2015 to current year(2016)
=> Update: Copyright Year from 2015 to 2016

lib/templates/helpers/rpad.js, lib/templates/std/help-generic.std, lib/templates/std/help.std, package.json, test/renderers/StandardRenderer.js, test/util/template.js
=> Handlebars vulnerability

lib/core/scripts.js, package.json, test/core/scripts.js
Hi @sheerun , this PR is for supporting shell operators in preinstall, postinstall and preuninstall hooks, and fixes the issue #1594.
Thanks!
=> Fix hooks to support shell operators

Gruntfile.js
I think that if we are using the same files we could reuse them as in `watch`.
=> Reuse the files selected in jshint for jscs

lib/core/Manager.js
Implements feature from #1714 
Here's screencast:
=> implement the possibility to type the entire version when conflict occured

lib/commands/register.js, test/commands/register.js
=> Add support for registering package with github's orgname/reponame

lib/commands/version.js, lib/templates/json/help-version.json, test/commands/version.js, test/helpers.js
Fixes and squashes #2142 
@bower/contributors  and @hdgarrood please review
=> Make bower version behavior consistent with spec

lib/core/Project.js, lib/core/scripts.js, test/core/scripts.js
Implements feature from #1451.
=> Implement postuninstall hooks with tests

lib/commands/info.js, lib/commands/install.js, test/commands/info.js, test/commands/install.js
`@` is replaced with `#` as part of the `info` and `install` commands.
=> Allow `@` to be used as a divider with cli: install and info.

packages/bower-config/package.json, packages/bower-endpoint-parser/package.json, packages/bower-json/package.json, packages/bower-logger/package.json, packages/bower-registry-client/package.json
Currently the link to the repository on these packages are dead (eg see [bower-json](https://www.npmjs.com/package/bower-json) which links to [bower/json](https://github.com/bower/json).
This commit will fix the links to the code.
I'm not familiar enough with the NPM package structure if this is the best solution or if there are others. Optimally I would like to link directly to the subfolder ./packages/bower-json within bower/bower.
I'm fine if you do not want to merge this PR for whatever reason.
Johannes
=> Update package repository information

lib/core/resolvers/GitResolver.js
semver.neq throws error when version is not valid. It should be catched and logged or simply ignored by this check. I've been using npm-check-updates package and it crashes because of this:
```
C:\DEV>ncu -m bower
Unhandled rejection TypeError: Invalid Version: 2.2-jsdw
at new SemVer (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\semver\semver.js:273:11)
at compare (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\semver\semver.js:460:10)
at Object.neq (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\node_modules\semver\semver.js:504:10)
at GitHubResolver.GitResolver._savePkgMeta (C:\Users\jamat\AppData\Roaming\npm\node_modules\bower\lib\core\resolvers
\GitResolver.js:209:56)
at GitHubResolver._savePkgMeta …
```
=> Check if version is valid

lib/util/readJson.js
Enhancement regarding #2355 
Add a warning message and show jsonFile before showing `issues.warnings`
Here is what it looks like after this PR:
=> add warning message to show which file the warning comes from

lib/core/Project.js, test/commands/uninstall.js
- 1 unit test to see if it works
=> Fix #2352 - add the functionality of removing with git address

lib/core/resolvers/GitResolver.js, test/core/resolvers/gitResolver.js
Fix #2360 by reverting "set GIT_SSL_NO_VERIFY for opposite value than strictSsl"
This reverts commit f0a54d0018927f8f1cf85cb6c7e12a37cea49333 and adds some comments in the tests
=> Fix #2360 by reverting "set GIT_SSL_NO_VERIFY for opposite value than

lib/core/resolvers/GitHubResolver.js, lib/core/resolvers/GitResolver.js
This fixes #2247 as git checkout often fails on older git versions.
Additionally .tar.gz archives are downloaded for commits and branches.
=> Download tar archives from https://github when possible

lib/core/Manager.js, test/core/Manager.js
When a project has multiple dependencies on the same package, we try to find one that resolves to a version that also satisfies all of the other constraints. Dependencies are checked in the order that they were resolved, which is dependent on network latency and essentially random. If there are multiple valid resolutions, running `bower install` with the same `bower.json` file won't always produce the same result, which can lead to inconsistent behaviour across environments.
If one of the dependencies specifies an exact version, we should prefer it over others that specify a range of versions. This is consistent with how we already deprioritise wildcard targets - we want to choose the most specific target of the highest version which resolves correctly.
=> Prefer exact versions when dissecting dependencies

README.md
Might also be worth doing:
```sh
npm deprecate bower "..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!"
```
=>  Add yarn and webpack recommendation from bower.io to readme Fixes #2298

lib/core/resolvers/pluginResolverFactory.js
There is a small typo in lib/core/resolvers/pluginResolverFactory.js.
Should read `whether` rather than `wheter`.
=> docs: Fix simple typo, wheter -> whether

packages/bower-json/CHANGELOG.md
Versions in the changelog for bower-json seem wrong.
=> Fix typos in changelog

.github/workflows/nodejs.yml
All currently supported Node versions were missing from CI version matrix. Add them.
This lead to realization that GIthub Action runner for MacOS-latest does not support Node.js versions older than 16 any more. To keep the old versions supported, pin them to older version MacOS-13, which is the latest version with correct architecture to run those versions.
All Windows actions seem to fail for unrelated reason. They fail on master of Bower as well, so it is not a question changes in this PR.
=> CI: add Node.js 18, 20 & 22
